server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /load-api/ {
        proxy_pass http://sushi-load-generator.sushi.svc.cluster.local/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_connect_timeout 5s;
        proxy_read_timeout 10s;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
