apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/your-org/devops-sushi-api
    newName: devops-sushi-api
    newTag: local
  - name: ghcr.io/your-org/devops-sushi-load
    newName: devops-sushi-load
    newTag: local
