apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sushi-api
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - sushi
  selector:
    matchLabels:
      app.kubernetes.io/name: sushi-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
