apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - servicemonitor.yaml
  - sushi-alerts.yaml
  - prometheus-lb.yaml

configMapGenerator:
  - name: sushi-grafana-dashboard
    namespace: monitoring
    files:
      - grafana-dashboard-sushi.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
