apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sushi-api
  namespace: sushi
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sushi-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
